dataset: "pacs"
data_dir: "./dataset/data_folder/pacs"

model_name: "module_small_patch16_224"
num_experts: 6
expert_depth: 2
expert_hidden_ratio: 0.10
gate_k: 2

lambda_sparse: 0.1
lambda_balance: 0.1
lambda_div: 0.1

pretrained: true

unlearn_setting: "random"
forget_ratio: 0.10  

epochs: 50
batch_size: 32
lr: 5.0e-4
seed: 42

# epoch [6/50] | total_loss: 0.4175 (ce: 0.3652, sp: 0.1232, bal: 0.3922, div: 0.0072) | ra: 91.03% | fa: 90.61% | ta: 85.19% | mia: 0.5569 | time: 84.03s