dataset: "pacs"
data_dir: "./dataset/data_folder/pacs"

model_name: "asu_deit_small_patch16_224"
pretrained: true

unlearn_setting: "random"
forget_ratio: 0.10  

epochs: 100
batch_size: 32
lr: 5.0e-4
seed: 42

