dataset: "pacs"
data_dir: "./dataset/data_folder/pacs"

model_name: "module_small_patch16_224"
moe_layers: "FFFFFFFFSFSF"

num_experts: 12
expert_depth: 2
expert_hidden_ratio: 0.10
gate_k: 4

pretrained_model_path: "/root/KhaiDD/unlearning_benchmark/unlearning_benchmark/checkpoint/config/ablation/expert_selection_rules/learn/expert_selection_rules/expert_selection_rules_epoch_100.pt"

unlearn_algo: "module_unlearn_algo"

unlearn_setting: "random"
forget_ratio: 0.10

# unlearn_setting: "class"
# forget_classes: [3]

# unlearn_setting: "domain"
# forget_domaines: [1]

beta: 0.5
gamma: 0.5
eta: 0.5
k_u: 4

epochs: 500
batch_size: 32
lr: 2.0e-4
fa_threshold: 0.70
seed: 42

# ablation config
selection_option: "diff"                 
alpha: 0.0
update_scope: "selected_experts_only" 